language: python
dist: xenial
python:
- 2.7
install:
- pip install pipenv
- pipenv install --dev
- pipenv graph
script: pipenv run py.test -v
deploy:
  provider: pypi
  user: uc-ctds
  password:
    secure: IViFSlFGruFAnXAg442NaOwWB/9x/luOKoRsN9dz/EKu7mL3mMlROv/1yWDAybuhkH3jeZkkWekjQButqxVNmeUAzY8acqHK1dU3zFU5fd6qJFhOgxZIFVo5E4pbpS+2MsJW4h1wCMPny2IfLp/evu/X83+5pU/KpJtNYKxat2Gyn18WZKAyqdYY/seilw1k44VACfsfrVPE6tYhpwhBpOinjQw5B9jifm2xXvA+j3y2xdDev/TQ377kpURx8fa3URTmn+wPn2pRwnM2nxETv2686Tw5TQ7barMyB5yOgT78s+FAmh/f8nttLtOvqwfwl3ErP6qY2U+m+2b+LL8+AhR8O/OC+t2On0BRWs4FGWSmaPh8tqpfygTLEqys7YGVPasj5WF/KpahgG7RjtllpkUcQP6txjp9sIqMHW0NphJ8mE067At30sXoqD36eGaWMAW0c1ah56Vi1ZAqCmLW+COytdwAe7arUQ3U5rGPfyqWyJ7gU//kwMdrQioXRFsJY/fiqCdS+lBA5TWUmMaPmDWlsUJ7YqBa46uc8MlanrKo9fRdD9y1W6VuCshQ3LOXFLtw07F+XXExyq67+e3ZxLXkpzsVB5b6zK1V43ojUieUEyfajJQp9zLSWXs1bIuP79acjdUgnfszZxGIhKR/ktdS98oAHR7t7Lq51eE0SAM=
  skip_existing: true
  on:
    tags: true
